# ==========================================================
# GPT Model
# ==========================================================

[GPTConfig]

# Vocabulary
vocab_size = 0

# Sequence
max_len = 128

# Model
d_model = 256
n_heads = 8
n_layers = 6
d_ff = 1024

# Regularization
dropout = 0.1

# Special tokens
pad_token_id = 0
bos_token_id = 0
eos_token_id = 2

# Quantization Noise
use_quant_noise = false
quant_noise_p = 0.0
quant_noise_block_size = 8


# ==========================================================
# Training
# ==========================================================

[GPTTrainingConfig]

workdir = "path/to/workdir"

batch_size = 32
learning_rate = 1e-4
weight_decay = 0.01
num_epochs = 50
seed = 42
early_stopping = true
early_stopping_patience = 10
scheduler = "cosine"   # "none", "linear", "cosine", "exponential", "plateau"
gradient_clip_value = 1.0
# max_grad_norm = 1.0
num_workers = 0
plot_training_history = true

# For resume job, either use resume=true, or specify a path of checkpoint to resume_from
[GPTTrainingConfig.Resume]
resume = true
resume_checkpoint = "gpt_training/checkpoints/last_model.pt"


[GPTTrainingConfig.Finetune]
fine_tune = false
base_checkpoint = "path/to/zinc_pretrained.pt"  # Starting from and freezing this checkpoints for Finetune

fine_tune_method = "lora" # "lora" # current only support lora

fine_tune_lm_head = true     # True for full rank fine tuning
fine_tune_layer_norm = true  # True for full rank fine tuning


[GPTTrainingConfig.Finetune.Lora]
lora_target = "attention"  # "attention", "ffn", or "all"
lora_r = 8
lora_alpha = 16
lora_dropout = 0.05
lora_use_k_proj = false

lora_ffn_r = 4
lora_ffn_alpha = 16
lora_use_fc2 = false



# ==========================================================
# Dataset
# ==========================================================

[DatasetConfig]

dataset_path = "dataset/combined/combined_pivot.parquet"

smiles_column = "SMILES"

training_X = "train_smiles"
validation_X = "val_smiles"

training_y = "train_labels"
validation_y = "val_labels"

val_fraction = 0.1

max_length = 128

preprocess_batch_size = 100000

seed = 42


# ==========================================================
# Tokenizer
# ==========================================================

[TokenizerConfig]

tokenizer_name = "seyonec/ChemBERTa_zinc250k_v2_40k"

max_length = 128

condition_tokens = []


# ==========================================================
# Generation
# ==========================================================

[GPTGenerationConfig]

max_gen_len = 128

temperature = 1.0

top_k = 50

top_p = 0.95

