# Copyright (c) 2026 Yonglan Liu
# Licensed under the MIT License.

from __future__ import annotations

from typing import Iterable, Sequence

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.feature_selection import VarianceThreshold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from src.chemflow.featurization import (
    FP_TYPES,
    MACCS_TYPES,
    DESC_TYPES,
    FP_BITS,
    DESC_NAMES,
    smiles_to_fp,
    smiles_to_descriptors,
    smiles_to_maccs,
)


# ============================================================
# Feature-type helpers
# ============================================================

def _normalize_feature_types(
    feature_types: str | Sequence[str] | None,
) -> list[str]:
    """
    Normalize feature type input.

    Examples
    --------
    None
        -> ["ecfp4"]

    "ecfp4"
        -> ["ecfp4"]

    ["ecfp4", "descriptors"]
        -> ["ecfp4", "descriptors"]
    """
    if feature_types is None:
        return ["ecfp4"]

    if isinstance(feature_types, str):
        feature_types = [feature_types]

    return [
        str(feature_type).lower().strip()
        for feature_type in feature_types
    ]


def is_descriptor_feature(feature_type: str) -> bool:
    feature_type = str(feature_type).lower().strip()

    return (
        feature_type in DESC_TYPES
        or feature_type in {"descriptor", "descriptors"}
    )


def is_fingerprint_feature(feature_type: str) -> bool:
    feature_type = str(feature_type).lower().strip()

    return (
        feature_type in FP_TYPES
        or feature_type in MACCS_TYPES
        or feature_type in {"maccs", "macc"}
    )


def get_feature_dimension(feature_type: str) -> int:
    """
    Return the number of columns generated by one feature type.
    """
    feature_type = str(feature_type).lower().strip()

    if is_descriptor_feature(feature_type):
        return len(DESC_NAMES)

    if feature_type in FP_TYPES:
        return int(FP_BITS[feature_type])

    if feature_type in MACCS_TYPES or feature_type in {"maccs", "macc"}:
        return int(FP_BITS["maccs"])

    raise ValueError(
        f"Unknown feature type: {feature_type}"
    )


def get_total_feature_dimension(
    feature_types: str | Sequence[str] | None,
) -> int:
    feature_types = _normalize_feature_types(feature_types)

    return sum(
        get_feature_dimension(feature_type)
        for feature_type in feature_types
    )


def get_feature_column_indices(
    feature_types: str | Sequence[str] | None,
) -> dict[str, list[int]]:
    """
    Return descriptor and fingerprint column indices for the raw
    concatenated feature matrix.

    Feature order follows `feature_types`.
    """
    feature_types = _normalize_feature_types(feature_types)

    descriptor_indices: list[int] = []
    fingerprint_indices: list[int] = []

    current_start = 0

    for feature_type in feature_types:
        n_features = get_feature_dimension(feature_type)

        current_indices = list(
            range(
                current_start,
                current_start + n_features,
            )
        )

        if is_descriptor_feature(feature_type):
            descriptor_indices.extend(current_indices)

        elif is_fingerprint_feature(feature_type):
            fingerprint_indices.extend(current_indices)

        else:
            raise ValueError(
                f"Unknown feature type: {feature_type}"
            )

        current_start += n_features

    return {
        "descriptor": descriptor_indices,
        "fingerprint": fingerprint_indices,
    }


# ============================================================
# Single-molecule featurization
# ============================================================

def _featurize_single_smiles(
    smi,
    feature_types: str | Sequence[str] | None,
):
    """
    Convert one SMILES into a concatenated molecular feature vector.

    Returns
    -------
    np.ndarray | None
        1D float32 feature vector, or None if featurization fails.
    """
    feature_types = _normalize_feature_types(feature_types)

    mol_features = []

    for feature_type in feature_types:

        if feature_type == "ecfp4":
            x = smiles_to_fp(
                smi,
                radius=2,
                n_bits=FP_BITS["ecfp4"],
                use_features=False,
            )

        elif feature_type == "ecfp6":
            x = smiles_to_fp(
                smi,
                radius=3,
                n_bits=FP_BITS["ecfp6"],
                use_features=False,
            )

        elif feature_type == "fcfp4":
            x = smiles_to_fp(
                smi,
                radius=2,
                n_bits=FP_BITS["fcfp4"],
                use_features=True,
            )

        elif feature_type == "fcfp6":
            x = smiles_to_fp(
                smi,
                radius=3,
                n_bits=FP_BITS["fcfp6"],
                use_features=True,
            )

        elif feature_type in MACCS_TYPES or feature_type in {"maccs", "macc"}:
            x = smiles_to_maccs(smi)

        elif is_descriptor_feature(feature_type):
            x = smiles_to_descriptors(smi)

        else:
            raise ValueError(
                f"Unknown feature_type: {feature_type}"
            )

        if x is None:
            return None

        x = np.asarray(
            x,
            dtype=np.float32,
        ).ravel()

        if not np.all(np.isfinite(x)):
            return None

        mol_features.append(x)

    if not mol_features:
        return None

    return np.concatenate(
        mol_features,
        axis=0,
    ).astype(np.float32)


# ============================================================
# DataFrame featurization
# ============================================================

def featurize_dataframe(
    df: pd.DataFrame,
    smiles_col: str = "SMILES",
    feature_types: str | Sequence[str] | None = None,
):
    """
    Featurize molecules from a DataFrame.

    Supports
    --------
    - ECFP4
    - ECFP6
    - FCFP4
    - FCFP6
    - MACCS
    - descriptors

    Returns
    -------
    X : np.ndarray
        Shape: (n_valid_molecules, n_features)

    clean_df : pd.DataFrame
        DataFrame containing only molecules that were successfully
        featurized.
    """
    feature_types = _normalize_feature_types(feature_types)

    if smiles_col not in df.columns:
        raise KeyError(
            f"SMILES column '{smiles_col}' was not found."
        )

    X_list = []
    valid_indices = []

    for idx, smi in df[smiles_col].items():

        x = _featurize_single_smiles(
            smi,
            feature_types,
        )

        if x is None:
            continue

        X_list.append(x)
        valid_indices.append(idx)

    if len(X_list) == 0:
        return None, None

    X = np.vstack(
        X_list
    ).astype(np.float32)

    clean_df = (
        df.loc[valid_indices]
        .copy()
    )

    return X, clean_df


# ============================================================
# Array featurization
# ============================================================

def featurize_array(
    X: np.ndarray,
    y: np.ndarray,
    feature_types: str | Sequence[str] | None = None,
):
    """
    Featurize SMILES stored in an array.

    Parameters
    ----------
    X
        Array-like SMILES.

    y
        Array-like labels.

    feature_types
        Molecular representation(s).

    Returns
    -------
    X_features : np.ndarray
        Molecular features.

    y_clean : np.ndarray
        Labels corresponding only to valid molecules.

    valid_indices : np.ndarray
        Original positions retained after featurization.
    """
    feature_types = _normalize_feature_types(feature_types)

    X = np.asarray(X)
    y = np.asarray(y)

    if len(X) != len(y):
        raise ValueError(
            f"X and y must have the same length, "
            f"got {len(X)} and {len(y)}."
        )

    X_features = []
    y_clean = []
    valid_indices = []

    for idx, smi in enumerate(X):

        x = _featurize_single_smiles(
            smi,
            feature_types,
        )

        if x is None:
            continue

        X_features.append(x)
        y_clean.append(y[idx])
        valid_indices.append(idx)

    if len(X_features) == 0:
        return None, None, None

    X_features = np.vstack(
        X_features
    ).astype(np.float32)

    y_clean = np.asarray(y_clean)

    valid_indices = np.asarray(
        valid_indices,
        dtype=np.int64,
    )

    return (
        X_features,
        y_clean,
        valid_indices,
    )


# ============================================================
# Separate descriptor / fingerprint featurization
# ============================================================

def split_feature_matrix(
    X: np.ndarray,
    feature_types: str | Sequence[str] | None,
) -> dict[str, np.ndarray | None]:
    """
    Split a raw concatenated feature matrix into descriptor and
    fingerprint blocks.

    This is useful for Graphormer when descriptors and fingerprints
    are sent through separate neural-network branches.
    """
    feature_types = _normalize_feature_types(feature_types)

    indices = get_feature_column_indices(feature_types)

    X = np.asarray(
        X,
        dtype=np.float32,
    )

    descriptor_indices = indices["descriptor"]
    fingerprint_indices = indices["fingerprint"]

    descriptor_features = (
        X[:, descriptor_indices]
        if descriptor_indices
        else None
    )

    fingerprint_features = (
        X[:, fingerprint_indices]
        if fingerprint_indices
        else None
    )

    return {
        "descriptors": descriptor_features,
        "fingerprints": fingerprint_features,
    }


# ============================================================
# Shared preprocessing
# ============================================================

def make_feature_preprocessor(
    feature_types: str | Sequence[str] | None,
    *,
    fingerprint_variance_threshold: float | None = None,
) -> ColumnTransformer:
    """
    Build a reusable feature preprocessor.

    This preprocessor can be used by both:

        1. regular sklearn ML
        2. Graphormer / PyTorch

    Rules
    -----
    Descriptors:
        StandardScaler

    Fingerprints:
        no scaling

        Optionally apply VarianceThreshold to remove invariant or
        near-invariant fingerprint bits.

    Important
    ---------
    Fit this preprocessor ONLY on the training set.

    For cross-validation, each fold must fit its own preprocessor.
    """
    feature_types = _normalize_feature_types(feature_types)

    indices = get_feature_column_indices(feature_types)

    descriptor_indices = indices["descriptor"]
    fingerprint_indices = indices["fingerprint"]

    transformers = []

    # --------------------------------------------------------
    # Descriptor branch
    # --------------------------------------------------------
    if descriptor_indices:

        descriptor_pipeline = Pipeline(
            steps=[
                (
                    "scaler",
                    StandardScaler(),
                ),
            ]
        )

        transformers.append(
            (
                "descriptors",
                descriptor_pipeline,
                descriptor_indices,
            )
        )

    # --------------------------------------------------------
    # Fingerprint branch
    # --------------------------------------------------------
    if fingerprint_indices:

        if fingerprint_variance_threshold is None:

            fingerprint_transformer = "passthrough"

        else:

            fingerprint_transformer = Pipeline(
                steps=[
                    (
                        "variance_filter",
                        VarianceThreshold(
                            threshold=float(
                                fingerprint_variance_threshold
                            )
                        ),
                    ),
                ]
            )

        transformers.append(
            (
                "fingerprints",
                fingerprint_transformer,
                fingerprint_indices,
            )
        )

    if not transformers:
        raise ValueError(
            "No supported molecular features were found."
        )

    # Explicitly control output order:
    #
    #     descriptors first
    #     fingerprints second
    #
    # This is independent of their order in feature_types.
    return ColumnTransformer(
        transformers=transformers,
        remainder="drop",
        sparse_threshold=0.0,
    )


# ============================================================
# Regular ML pipeline
# ============================================================

def make_scaled_pipeline(
    model,
    feature_types: str | Sequence[str] | None,
    *,
    fingerprint_variance_threshold: float | None = None,
):
    """
    Create the sklearn training pipeline.

    Rules
    -----
    Fingerprints only:
        passed through without scaling.

    Descriptors only:
        StandardScaler.

    Mixed descriptor + fingerprint:
        descriptors are standardized;
        fingerprints remain binary.

    Optional fingerprint variance filtering is supported.

    This keeps preprocessing inside the sklearn Pipeline, which
    prevents train/validation leakage during CV.
    """
    preprocessor = make_feature_preprocessor(
        feature_types=feature_types,
        fingerprint_variance_threshold=(
            fingerprint_variance_threshold
        ),
    )

    return Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor,
            ),
            (
                "model",
                model,
            ),
        ]
    )


# ============================================================
# Graphormer preprocessing helpers
# ============================================================

def fit_graphormer_preprocessor(
    X_train: np.ndarray,
    feature_types: str | Sequence[str] | None,
    *,
    fingerprint_variance_threshold: float | None = None,
):
    """
    Fit preprocessing on Graphormer training features only.

    Returns
    -------
    preprocessor
        Fitted sklearn ColumnTransformer.

    X_train_processed
        Processed float32 training features.
    """
    preprocessor = make_feature_preprocessor(
        feature_types=feature_types,
        fingerprint_variance_threshold=(
            fingerprint_variance_threshold
        ),
    )

    X_train_processed = (
        preprocessor
        .fit_transform(X_train)
    )

    X_train_processed = np.asarray(
        X_train_processed,
        dtype=np.float32,
    )

    return (
        preprocessor,
        X_train_processed,
    )


def transform_graphormer_features(
    preprocessor,
    X: np.ndarray,
) -> np.ndarray:
    """
    Transform validation, test, or prediction features using a
    preprocessor already fitted on training data.
    """
    if preprocessor is None:
        raise ValueError(
            "preprocessor cannot be None."
        )

    X_processed = (
        preprocessor
        .transform(X)
    )

    return np.asarray(
        X_processed,
        dtype=np.float32,
    )


def get_processed_feature_dimensions(
    preprocessor,
    X_reference: np.ndarray,
    feature_types: str | Sequence[str] | None,
) -> dict[str, int]:
    """
    Determine descriptor and fingerprint dimensions AFTER fitted
    preprocessing.

    This matters if VarianceThreshold removes fingerprint bits.

    The preprocessor output order is:

        descriptors | fingerprints
    """
    feature_types = _normalize_feature_types(feature_types)

    raw_indices = get_feature_column_indices(
        feature_types
    )

    raw_desc_dim = len(
        raw_indices["descriptor"]
    )

    raw_fp_dim = len(
        raw_indices["fingerprint"]
    )

    if raw_desc_dim == 0 and raw_fp_dim == 0:
        return {
            "descriptor_dim": 0,
            "fingerprint_dim": 0,
            "total_dim": 0,
        }

    X_reference = np.asarray(
        X_reference,
        dtype=np.float32,
    )

    transformed = np.asarray(
        preprocessor.transform(
            X_reference[:1]
        ),
        dtype=np.float32,
    )

    total_dim = int(
        transformed.shape[1]
    )

    # Descriptor scaling never changes descriptor dimensionality.
    descriptor_dim = raw_desc_dim

    fingerprint_dim = (
        total_dim - descriptor_dim
    )

    return {
        "descriptor_dim": descriptor_dim,
        "fingerprint_dim": fingerprint_dim,
        "total_dim": total_dim,
    }


def split_processed_features(
    X_processed: np.ndarray,
    descriptor_dim: int,
) -> dict[str, np.ndarray | None]:
    """
    Split already-processed features into Graphormer descriptor and
    fingerprint inputs.

    make_feature_preprocessor() guarantees the output order:

        descriptors | fingerprints

    Parameters
    ----------
    X_processed
        Preprocessed feature matrix.

    descriptor_dim
        Number of descriptor columns after preprocessing.
        StandardScaler does not change this dimension.

    Returns
    -------
    dict
        {
            "descriptors": ...,
            "fingerprints": ...
        }
    """
    X_processed = np.asarray(
        X_processed,
        dtype=np.float32,
    )

    descriptor_dim = int(
        descriptor_dim
    )

    if descriptor_dim < 0:
        raise ValueError(
            "descriptor_dim must be >= 0."
        )

    if descriptor_dim > X_processed.shape[1]:
        raise ValueError(
            f"descriptor_dim={descriptor_dim} exceeds "
            f"processed feature dimension "
            f"{X_processed.shape[1]}."
        )

    descriptors = (
        X_processed[:, :descriptor_dim]
        if descriptor_dim > 0
        else None
    )

    fingerprints = (
        X_processed[:, descriptor_dim:]
        if descriptor_dim < X_processed.shape[1]
        else None
    )

    return {
        "descriptors": descriptors,
        "fingerprints": fingerprints,
    }


# ============================================================
# Convenience: complete Graphormer feature preparation
# ============================================================

def prepare_graphormer_features(
    train_df: pd.DataFrame,
    val_df: pd.DataFrame | None = None,
    test_df: pd.DataFrame | None = None,
    *,
    smiles_col: str = "SMILES",
    feature_types: str | Sequence[str] | None = None,
    fingerprint_variance_threshold: float | None = None,
):
    """
    Complete train/validation/test feature-preparation workflow for
    Graphormer.

    The preprocessor is fitted ONLY on the training set.

    Returns
    -------
    dict
        Contains:
            preprocessor
            train_features
            val_features
            test_features
            train_df
            val_df
            test_df
            descriptor_dim
            fingerprint_dim
            total_dim

    Notes
    -----
    If mixed features are used, output order is always:

        scaled descriptors | fingerprints
    """
    feature_types = _normalize_feature_types(
        feature_types
    )

    # --------------------------------------------------------
    # Training set
    # --------------------------------------------------------
    X_train_raw, clean_train_df = featurize_dataframe(
        train_df,
        smiles_col=smiles_col,
        feature_types=feature_types,
    )

    if X_train_raw is None:
        raise ValueError(
            "No valid molecules were found in the training set."
        )

    preprocessor, X_train_processed = (
        fit_graphormer_preprocessor(
            X_train=X_train_raw,
            feature_types=feature_types,
            fingerprint_variance_threshold=(
                fingerprint_variance_threshold
            ),
        )
    )

    dims = get_processed_feature_dimensions(
        preprocessor=preprocessor,
        X_reference=X_train_raw,
        feature_types=feature_types,
    )

    # --------------------------------------------------------
    # Validation set
    # --------------------------------------------------------
    clean_val_df = None
    X_val_processed = None

    if val_df is not None:

        X_val_raw, clean_val_df = featurize_dataframe(
            val_df,
            smiles_col=smiles_col,
            feature_types=feature_types,
        )

        if X_val_raw is not None:
            X_val_processed = (
                transform_graphormer_features(
                    preprocessor,
                    X_val_raw,
                )
            )

    # --------------------------------------------------------
    # Test set
    # --------------------------------------------------------
    clean_test_df = None
    X_test_processed = None

    if test_df is not None:

        X_test_raw, clean_test_df = featurize_dataframe(
            test_df,
            smiles_col=smiles_col,
            feature_types=feature_types,
        )

        if X_test_raw is not None:
            X_test_processed = (
                transform_graphormer_features(
                    preprocessor,
                    X_test_raw,
                )
            )

    return {
        "preprocessor": preprocessor,
        "train_features": X_train_processed,
        "val_features": X_val_processed,
        "test_features": X_test_processed,
        "train_df": clean_train_df,
        "val_df": clean_val_df,
        "test_df": clean_test_df,
        "descriptor_dim": dims["descriptor_dim"],
        "fingerprint_dim": dims["fingerprint_dim"],
        "total_dim": dims["total_dim"],
        "feature_types": feature_types,
    }


# ============================================================
# Example usage
# ============================================================

if __name__ == "__main__":

    # --------------------------------------------------------
    # Example molecular feature configuration
    # --------------------------------------------------------
    feature_types = [
        "descriptors",
        "ecfp4",
    ]

    print(
        "Feature types:",
        feature_types,
    )

    print(
        "Raw total feature dimension:",
        get_total_feature_dimension(
            feature_types
        ),
    )

    print(
        "Raw feature indices:",
        get_feature_column_indices(
            feature_types
        ),
    )

    # --------------------------------------------------------
    # Example:
    #
    # result = prepare_graphormer_features(
    #     train_df=train_df,
    #     val_df=val_df,
    #     test_df=test_df,
    #     smiles_col="SMILES",
    #     feature_types=["descriptors", "ecfp4"],
    #     fingerprint_variance_threshold=None,
    # )
    #
    # X_train = result["train_features"]
    # X_val = result["val_features"]
    #
    # descriptor_dim = result["descriptor_dim"]
    #
    # train_blocks = split_processed_features(
    #     X_train,
    #     descriptor_dim=descriptor_dim,
    # )
    #
    # descriptor_features = train_blocks["descriptors"]
    # fingerprint_features = train_blocks["fingerprints"]
    #
    # These can then be converted to torch.Tensor and attached
    # to each Graphormer batch.
    # --------------------------------------------------------
