from __future__ import annotations

import os
import sys
import tomllib
from dataclasses import fields
from pathlib import Path
from typing import Any, TypeVar

import torch
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, DistributedSampler
from transformers import AutoTokenizer

from src.chemflow.machine_learning.llm.rnn import SmilesLSTMGenerator
from src.chemflow.machine_learning.train.trainer_llm import (
    get_lstm_config,
    load_pretrained_for_finetune,
    load_or_cache_dataset,
    run_ce_training,
    run_reward_training,
    build_scheduler,
)
from src.chemflow.machine_learning.configs import (
    LLMTrainingConfig,
    TokenizerConfig,
    GenerationConfig,
    LSTMConfig,
)
from src.chemflow.machine_learning.data.dataset import SmilesDataset


T = TypeVar("T")


# ============================================================
# Config Helpers
# ============================================================

def load_toml_config(config_path: str | Path) -> dict[str, Any]:
    config_path = Path(config_path).expanduser().resolve()

    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_path, "rb") as f:
        return tomllib.load(f)


def build_dataclass_from_dict(cls: type[T], data: dict[str, Any] | None) -> T:
    """
    Safely initialize dataclass from dict.

    Extra TOML keys are ignored.
    Missing TOML keys use dataclass defaults.
    """
    if data is None:
        data = {}

    valid_fields = {f.name for f in fields(cls)}
    clean_data = {k: v for k, v in data.items() if k in valid_fields}

    return cls(**clean_data)


def load_all_configs(config_path: str | Path | None):
    """
    Supports the TOML generated by your Streamlit page:

    [training_config]
    ...

    [tokenizer_config]
    ...

    [model_config]
    ...

    [generation_config]
    ...
    """
    if config_path is None:
        return (
            LLMTrainingConfig(),
            TokenizerConfig(),
            GenerationConfig(),
            LSTMConfig(),
        )

    cfg = load_toml_config(config_path)

    training_config = build_dataclass_from_dict(
        LLMTrainingConfig,
        cfg.get("training_config", {}),
    )

    tokenizer_config = build_dataclass_from_dict(
        TokenizerConfig,
        cfg.get("tokenizer_config", {}),
    )

    generation_config = build_dataclass_from_dict(
        GenerationConfig,
        cfg.get("generation_config", {}),
    )

    lstm_config = build_dataclass_from_dict(
        LSTMConfig,
        cfg.get("model_config", {}),
    )

    return training_config, tokenizer_config, generation_config, lstm_config


# ============================================================
# DDP Helpers
# ============================================================

def is_ddp_run() -> bool:
    return "LOCAL_RANK" in os.environ and "RANK" in os.environ and "WORLD_SIZE" in os.environ


def setup_distributed():
    """
    Works for both:
    1. Single GPU / CPU:
       python train.py config.toml

    2. Multi-GPU DDP:
       torchrun --standalone --nproc_per_node=4 train.py config.toml
    """
    if is_ddp_run():
        dist.init_process_group(backend="nccl")

        local_rank = int(os.environ["LOCAL_RANK"])
        rank = int(os.environ["RANK"])
        world_size = int(os.environ["WORLD_SIZE"])

        torch.cuda.set_device(local_rank)
        device = torch.device(f"cuda:{local_rank}")

        return device, local_rank, rank, world_size, True

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return device, 0, 0, 1, False


def cleanup_distributed() -> None:
    if dist.is_available() and dist.is_initialized():
        dist.destroy_process_group()


def is_main_process(rank: int) -> bool:
    return rank == 0


def unwrap_model(model):
    return model.module if isinstance(model, DDP) else model


# ============================================================
# Tokenizer Helpers
# ============================================================

def prepare_tokenizer(tokenizer_config: TokenizerConfig):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_config.tokenizer_name)

    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token or tokenizer.sep_token

    if tokenizer.bos_token_id is None:
        tokenizer.bos_token = tokenizer.cls_token or tokenizer.eos_token

    if tokenizer.eos_token_id is None:
        tokenizer.eos_token = tokenizer.sep_token or tokenizer.bos_token

    condition_tokens = getattr(tokenizer_config, "condition_tokens", None)

    if condition_tokens:
        tokenizer.add_special_tokens(
            {"additional_special_tokens": condition_tokens}
        )

    return tokenizer


# ============================================================
# Main
# ============================================================

def main() -> None:
    config_path = sys.argv[1] if len(sys.argv) > 1 else None

    device, local_rank, rank, world_size, use_ddp = setup_distributed()

    try:
        (
            training_config,
            tokenizer_config,
            generation_config,
            lstm_config,
        ) = load_all_configs(config_path)

        work_dir = Path(training_config.work_dir).expanduser().resolve()
        cache_dir = Path(training_config.cache_dir).expanduser()
        checkpoint_dir = Path(training_config.checkpoint_dir).expanduser()

        if not cache_dir.is_absolute():
            cache_dir = work_dir / cache_dir

        if not checkpoint_dir.is_absolute():
            checkpoint_dir = work_dir / checkpoint_dir

        if is_main_process(rank):
            work_dir.mkdir(parents=True, exist_ok=True)
            cache_dir.mkdir(parents=True, exist_ok=True)
            checkpoint_dir.mkdir(parents=True, exist_ok=True)

            print("=" * 80)
            print(f"Config path: {config_path}")
            print(f"Work dir: {work_dir}")
            print(f"Cache dir: {cache_dir}")
            print(f"Checkpoint dir: {checkpoint_dir}")
            print(f"Device: {device}")
            print(f"DDP enabled: {use_ddp}")
            print(f"World size: {world_size}")
            print("=" * 80)

        if use_ddp:
            dist.barrier()

        tokenizer = prepare_tokenizer(tokenizer_config)

        cfg = get_lstm_config(
            vocab_size=len(tokenizer),
            pad_token_id=tokenizer.pad_token_id,
            bos_token_id=tokenizer.bos_token_id,
            eos_token_id=tokenizer.eos_token_id,
            lstm_config=lstm_config,
        )

        model = SmilesLSTMGenerator.build_model(cfg)

        if training_config.fine_tune:
            if is_main_process(rank):
                print(f"Fine-tuning from {training_config.pretrained_ckpt_path}")

            model = load_pretrained_for_finetune(
                model=model,
                ckpt_path=training_config.pretrained_ckpt_path,
                device=device,
            )

        model = model.to(device)

        if use_ddp:
            model = DDP(
                model,
                device_ids=[local_rank],
                output_device=local_rank,
                find_unused_parameters=False,
            )

        train_smiles, val_smiles = load_or_cache_dataset(training_config)

        train_dataset = SmilesDataset(
            smiles_list=train_smiles,
            tokenizer=tokenizer,
            max_length=tokenizer_config.max_length,
            condition_list=None,
            ignore_condition_loss=False,
        )

        val_dataset = SmilesDataset(
            smiles_list=val_smiles,
            tokenizer=tokenizer,
            max_length=tokenizer_config.max_length,
            condition_list=None,
            ignore_condition_loss=False,
        )

        if use_ddp:
            train_sampler = DistributedSampler(
                train_dataset,
                num_replicas=world_size,
                rank=rank,
                shuffle=True,
            )

            val_sampler = DistributedSampler(
                val_dataset,
                num_replicas=world_size,
                rank=rank,
                shuffle=False,
            )
        else:
            train_sampler = None
            val_sampler = None

        train_loader = DataLoader(
            train_dataset,
            batch_size=training_config.batch_size,
            shuffle=(train_sampler is None),
            sampler=train_sampler,
            num_workers=getattr(training_config, "num_workers", 0),
            pin_memory=torch.cuda.is_available(),
        )

        val_loader = DataLoader(
            val_dataset,
            batch_size=training_config.batch_size,
            shuffle=False,
            sampler=val_sampler,
            num_workers=getattr(training_config, "num_workers", 0),
            pin_memory=torch.cuda.is_available(),
        )

        optimizer = torch.optim.AdamW(
            model.parameters(),
            lr=training_config.learning_rate,
            weight_decay=training_config.weight_decay,
        )

        scheduler = build_scheduler(
            optimizer=optimizer,
            training_config=training_config,
            total_epochs=training_config.epochs_no_reward,
        )

        ce_history, best_ce_path = run_ce_training(
            model=model,
            train_loader=train_loader,
            val_loader=val_loader,
            optimizer=optimizer,
            scheduler=scheduler,
            training_config=training_config,
            checkpoint_dir=checkpoint_dir,
            device=device,
        )

        if use_ddp:
            dist.barrier()

        if training_config.epochs_with_reward > 0:
            if is_main_process(rank):
                print(f"Loading best CE model for reward training: {best_ce_path}")

            ckpt = torch.load(best_ce_path, map_location=device)

            state_dict = ckpt["model"]

            if any(k.startswith("module.") for k in state_dict.keys()):
                state_dict = {
                    k.replace("module.", "", 1): v
                    for k, v in state_dict.items()
                }

            unwrap_model(model).load_state_dict(state_dict)

            reward_lr = getattr(
                training_config,
                "reward_learning_rate",
                training_config.learning_rate * 0.1,
            )

            optimizer = torch.optim.AdamW(
                model.parameters(),
                lr=reward_lr,
                weight_decay=training_config.weight_decay,
            )

            scheduler = build_scheduler(
                optimizer=optimizer,
                training_config=training_config,
                total_epochs=training_config.epochs_with_reward,
            )

            rl_history, best_rl_path = run_reward_training(
                model=model,
                train_loader=train_loader,
                val_loader=val_loader,
                tokenizer=tokenizer,
                optimizer=optimizer,
                scheduler=scheduler,
                training_config=training_config,
                generation_config=generation_config,
                checkpoint_dir=checkpoint_dir,
                device=device,
                start_epoch=len(ce_history["epoch"]) + 1,
            )

            if is_main_process(rank):
                print(f"Best RL model saved at: {best_rl_path}")

        else:
            if is_main_process(rank):
                print(f"Best CE model saved at: {best_ce_path}")

    finally:
        cleanup_distributed()


if __name__ == "__main__":
    main()