# ============================================================
# Dataset
# ============================================================

[DatasetConfig]

dataset_path = "./dataset/combined/PI3K_combined_pivot.csv"

smiles_column = "SMILES"

training_X = "train_smiles"
validation_X = "val_smiles"

training_y = "train_labels"
validation_y = "val_labels"

val_fraction = 0.1

preprocess_batch_size = 100000

max_nodes = 64
multi_hop_max_dist = 5
spatial_pos_max = 1024

seed = 42


# ============================================================
# Featurizer
# ============================================================

[FeaturizerConfig]
multi_hop_max_dist = 5

remove_hs = true
reorder_atoms = false


# ============================================================
# Graphormer Encoder
# ============================================================

[GraphormerEncoderConfig]

num_atoms = 8192
num_edges = 8192
num_in_degree = 512
num_out_degree = 512

num_spatial = 1024
num_edge_dis = 128

edge_type = "multi_hop"
multi_hop_max_dist = 5

num_encoder_layers = 12

embedding_dim = 768
ffn_embedding_dim = 768

num_attention_heads = 32

dropout = 0.1
attention_dropout = 0.1
activation_dropout = 0.1

layerdrop = 0.0

encoder_normalize_before = false
pre_layernorm = false

apply_graphormer_init = true

activation_fn = "gelu"

freeze_layer_indices = []

traceable = false
last_state_only = true

use_quant_noise = false
q_noise = 0.0
qn_block_size = 8


# ============================================================
# Graphormer Denoiser
# ============================================================

[GraphormerDenoiserConfig]
hidden_dim = 768
num_atom_types = 120
num_bond_types = 6
bond_pair_mode = "sum"
dropout = 0.1


# ============================================================
# Diffusion
# ============================================================

[GraphormerDiffusionConfig]

num_timesteps = 50
atom_mask_token = 120
bond_mask_token = 6
atom_pad_token = 0
bond_pad_token = 0
atom_loss_weight = 1.0
bond_loss_weight = 1.0


# ============================================================
# Training
# ============================================================

[GraphormerDiffusionTrainingConfig]

workdir = "./training_example/diffusion_training"
seed = 42
batch_size = 16
eval_batch_size = 16
num_epochs = 50
learning_rate = 1e-5
weight_decay = 0.01
scheduler = "cosine"
early_stopping_patience = 10
num_workers = 0
plot_training_history = true
gradient_clip_value = 1.0
resume = true
# resume_checkpoint = "/path/to/resume_checkpoint"  # if not set, training will use default last_model.pt

